version: '3.8'

services:
  modal-ctf:
    build: .
    image: modal-ctf:secure
    container_name: modal-ctf
    restart: always  # Changed from unless-stopped for better CTF resilience
    ports:
      - "${HOST_PORT:-80}:8080"
    environment:
      - FLAG=${FLAG:-CTF{default_flag_for_testing}}
      - MODAL_TOKEN_ID=${MODAL_TOKEN_ID}
      - MODAL_TOKEN_SECRET=${MODAL_TOKEN_SECRET}
      - PORT=8080
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,nodev,size=10M
      - /run:noexec,nosuid,nodev,size=10M
    security_opt:
      - no-new-privileges:true
      # Note: AppArmor and Seccomp may not work on macOS
      # Uncomment these lines on Linux for additional security:
      # - apparmor:docker-default
      # - seccomp:default
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    mem_limit: 256m
    memswap_limit: 256m
    cpus: 0.5
    pids_limit: 50
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
      nproc:
        soft: 50
        hard: 50
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
